### ISSUE TITLE
Some settings stopped working in v1

### ISSUE THREAD

**Issue by fsgreco** [TylerBarnes/gatsby-wordpress-inline-images#4]
Unfortunately after the upgrade the images are all at 1024. I set "maxWidth: 550," but the plugin is still showing images at max size. 

This is my code inside gatsby-config.js

```Json
	{
	resolve: `gatsby-source-wordpress`,
	options: {
		baseUrl: `URL`,
		protocol: "https",
		hostingWPCOM: false,
		useACF: true,
		verboseOutput: false,
		plugins: [
			{
				resolve: `gatsby-wordpress-inline-images`,
				options: {
					baseUrl: `URL`,
					protocol: `https`,
					quality: 90,
					maxWidth: 550,
					tracedSVG: true,
				}
			}],
		excludedRoutes: [
			"/wp/v2/users", "/wp/v2/users/me", "/acf/v2/options", "/wp/v2/settings", "/yoast/v1/configurator", "/yoast/v1/reindex_posts", "/yoast/v1/statistics", "/yoast/v1/ryte"
		],
	}
},
```

**Comment by fsgreco** [comment]
I think that the problem derives from the fix that you have done in the responsive styles. Now my max width is setted as inline style with 1024 by default, instead of 650px, and seems that the srcset sizes are not working. (I have a main layout with css grid with a max-width of 1000px, but now the images max-width are messing with the main layout)

**Comment by cseebach-tpc** [comment]
@anonimoconiglio Not a great workaround, but are you okay doing a selective `!important` in your stylesheet until this gets fixed or adjusted?

**Comment by fsgreco** [comment]
@cseebach-tpc Thanks, it works although the main layout remains compromised for the mobile version: I think that since the width 1024 is inserted through an inline-style (inside the html structure) it extends the dimension of the main div (It's like there is still a div inside that tells the browser that it will take 1024px, and maybe since it's inline style it wins most of the css specificity?). 

With your solution the image will be rendered at 650 and worked fine for the desktop, but it will not stretch when going mobile.
Besides, I just realized that _it's not centered any more_ (In the wordpress version I get the image centered on the html content, now it starts at left).
	
This is the grid structure of my site (it's a simple main and sidebar website) 

```css
main {
  max-width: 1068px; /* 960 + 6rem (make up for padding) */
  margin: 0 auto;
  padding: 1.45rem 1rem 1.45rem;

  display: grid;
  grid-template-columns: 3fr 1fr;
  grid-gap: 2rem;
}

/* TEMPORAL FIX FOR IMAGES-INLINE-CSS */
main div.gatsby-image-wrapper {
	max-width: 650px !important; 
	margin: 0 auto; 
}
```

Anyway, for the moment I just don't updated the package (I'm still using the alpha, that worked fine for me).
